Source/WebScrapper/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebScrapper.Repositories;
using WebScrapper.ViewModel;

namespace WebScrapper.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        SelectorRepository _rep = new SelectorRepository();
        // GET: Admin

        public ActionResult Index()
        {
            var lstSelectors = _rep.GetSelectors();
            return View(lstSelectors);
        }

        public ActionResult CreateSelecor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateSelecor(SourceSelectorVM selector)
        {
            if(ModelState.IsValid)
            {
                var isNewAdded = _rep.SaveSelector(selector);
                if (isNewAdded)
                {
                    ViewBag.Message = "New Selector Added successfully";
                    ModelState.Clear();
                }
            }          
            return View();
        }

        public ActionResult Edit(int id)
        {
            var source = _rep.GetSelectorByID(id);
            return View(source);
        }

        [HttpPost]
        public ActionResult Edit(SourceSelectorVM model)
        {
            bool isUpdated = _rep.UpdateSelector(model);
            if (isUpdated)
            {
                return RedirectToAction("Index");
            }
            else
                return View();
        }

        public ActionResult Delete(int id)
        {
            bool isDeleted = _rep.DeleteUser(id);
            if (isDeleted)
                return RedirectToAction("Index");
            else
                return View();
        }
    }
}

Source/WebScrapper/Controllers/NewsController.cs
using Scrapper.Utility.Scrapper;
using System.Data;
using System.Web.Mvc;
using WebScrapper.Repositories;

namespace WebScrapper.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        NewsRepository _news = new NewsRepository();
        [Authorize]
       [AllowAnonymous]
        public ActionResult Index()
        {
          
            if (Session["User"] != null)
            {
                var lstNews = _news.GetNews();
                return View(lstNews);
            }else
            {
                return RedirectToAction("Login","User");
            }
            
        }

      

        public ActionResult ExportToExcel()
        {
            var lstNews = _news.GetNews();
            DataSet ds = Scrapper.Utility.Scrapper.Common.ToDataSet(lstNews);
            DataTable dt = ds.Tables[0];
            Scrapper.Utility.Scrapper.Common.WriteExcel(dt, "xls");
            return View();
        }


       
    }
}

Source/WebScrapper/Controllers/SubscriberController.cs
using Scrapper.DataAccess;
using Scrapper.Model.News;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebScrapper.Repositories;

namespace WebScrapper.Controllers
{
    [Authorize]
    public class SubscriberController : Controller
    {
        // GET: Subscriber
        SubscriberRepository _db = new SubscriberRepository();
        public ActionResult Index()
        {
            var lstSubscribers = _db.GetSubscribers();
            return View(lstSubscribers);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Subscriber model)
        {
            if (ModelState.IsValid)
            {
                bool isCreated = _db.Add(model);
                if (isCreated)
                    return RedirectToAction("Index");
                else
                    return View();
            }
            else
                return View();
        }

        //[ChildActionOnly]
        public ActionResult Delete(int id)
        {
            bool isDeleted = _db.DeleteSubscriber(id);
            if (isDeleted)
                return RedirectToAction("Index");
            else
                return View();
        }

        public ActionResult Edit(int id)
        {
            var source = _db.GetSubscriberById(id);
            return View(source);
        }

        [HttpPost]
        public ActionResult Edit(Subscriber model)
        {
            bool isUpdated = _db.UpdateSubscriber(model);
            if (isUpdated)
            {
                return RedirectToAction("Index");
            }
            else
                return View();
        }
    }
}

Source/WebScrapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Scraper</title>
            @Styles.Render("~/Content/css")
           
        <link href="~/Content/loginstyle.css" rel="stylesheet" />
    <link href="http://yadcf-showcase.appspot.com/resources/css/jquery.dataTables.10.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link href="http://yadcf-showcase.appspot.com/resources/css/dataTables.jqueryui.css" rel="stylesheet" />
    <link href="http://yadcf-showcase.appspot.com/resources/css/jquery-ui.1.9.0.css" rel="stylesheet" />
    @*<link href="http://yadcf-showcase.appspot.com/resources/css/jquery.dataTables.yadcf.css" rel="stylesheet" />*@
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    
    @Scripts.Render("~/bundles/modernizr")
    @*<link href="~/Content/scrapper.css" rel="stylesheet" />*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Scraper", "Index", "News", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["User"] != null)
                    {
                        var user = Session["User"] as Scrapper.DataAccess.User;
                        if (user != null && user.RoleId == 1)
                        {
                            <li>@Html.ActionLink("News", "Index", "News")</li>
                            <li>@Html.ActionLink("Sources", "Index", "Admin")</li>
                            <li>@Html.ActionLink("Users", "UsersList", "User")</li>
                            <li>@Html.ActionLink("Subscribers", "Index", "Subscriber")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("News", "Index", "News")</li>
                        }
                       
                    }
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            @*<p style="text-align: center;">&copy; @DateTime.Now.Year - Scrapper</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/datetime.js"></script>
   
    @RenderSection("scripts", required: false)
    @*<script src="~/Scripts/jquery.dataTables.yadcf.js"></script>*@
</body>
</html>